version: '3'
services:
  app:
    build:
      context: ./.docker/apache/
    image: apache
    ports:
      - 80:80
    volumes:
      - ./:/var/www/
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: project-mysql-db
      DB_USERNAME: app
      DB_PASSWORD: app
    links:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: project-mysql-db
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: app
    volumes:
          - ./.docker/mysql-data:/var/lib/mysql